server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/photos?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181


mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
   com.ryz2593.mapper: debug